In [4]:
import numpy as np

df = np.array([1,2,3,4]) #vector

print(df)

df.ndim

[1 2 3 4]


1

In [5]:
df = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(df)
df.ndim

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


3

In [ ]:
print(np.arange(1,11))

print(np.arange(1,11,2))

arr1 = np.arange(1,11,2)

print(np.array(arr1,dtype=bool))

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ True  True  True  True  True]


In [6]:
print(np.arange(1,13).reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
print(np.ones((3,4)))

np.ones((2,4))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.random((3,4))

array([[0.84915988, 0.61061405, 0.30258272, 0.30431279],
       [0.98877363, 0.33483724, 0.71496503, 0.87212964],
       [0.98163629, 0.58841772, 0.59299902, 0.31032919]])

In [8]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
item = np.arange(1,13,dtype = int).reshape(2,6)

item1 = np.arange(1,9,dtype = np.int32).reshape(2,2,2)

print(item.size)
print(item.shape)
print(item1)
print(item.itemsize)
print(item1.itemsize)
print(item1.ndim)
print(item.ndim)

12
(2, 6)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
4
3
2


In [10]:
print(item.dtype)
print(item1.dtype)

int64
int32


In [11]:
item.astype(np.int32)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]], dtype=int32)

In [12]:
#scalar function
item ** 2

item == 5

array([[False, False, False, False,  True, False],
       [False, False, False, False, False, False]])

In [ ]:
# Vector operation

num1 = np.arange(1,5).reshape(2,2)

num2 = np.arange(5,9).reshape(2,2)

print(num1)

print(num2)

num3 = num1 + num2

print(num3)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [13]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
np.prod(a1,axis=0)
np.prod(a1,axis=1)

array([437184.,  78771.,   4200.])

In [14]:
np.round(np.random.random((2,3))*100)

array([[94., 55., 30.],
       [70.,  8., 96.]])

In [16]:
np.floor(np.random.random((2,3))*100)

array([[92.,  9., 31.],
       [96., 54., 70.]])

In [17]:
arr = np.array([[0,1,2,3],
				[4,5,6,7],
                [8,9,10,11]
              ])

print(arr[::2,1::2])
print(arr[1,::3])
print(arr[:2,1:])
print(arr[:2,1::2])

[[ 1  3]
 [ 9 11]]
[4 7]
[[1 2 3]
 [5 6 7]]
[[1 3]
 [5 7]]


In [ ]:
a3 = np.arange(27).reshape(3,3,3)

print(a3[1])

print(a3[::2])

print(a3[0,1,:])

print(a3[1,:,1])

print(a3[2,1:,1:])

print(a3[::2,0,::2])

In [ ]:
for i in np.nditer(a3):
	print(i)